### ISSUE TITLE
yaml_body not parsing multiple manifests in one yaml file when using the `file` function from Terraform

### ISSUE THREAD

**Issue by MichaelTrip** [alekc/terraform-provider-kubectl#110]
Hello,

I have the following yaml file, as a example:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysbox-label-node
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysbox-node-labeler
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysbox-label-node-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sysbox-node-labeler
subjects:
- kind: ServiceAccount
  name: sysbox-label-node
  namespace: kube-system
---
# etc
```

I have placed this in a file and i try to deploy this with the `kubectl_manifest` resource by using the following HCL code:
```
resource "kubectl_manifest" "sysbox" {
    yaml_body = file("./kubernetes-manifests/sysbox/sysbox-install.yml")
}
```

But the resource is only applying the first manifest, the `ServiceAccount`:

Terraform will perform the following actions:
  ```
# kubectl_manifest.sysbox will be created
  + resource "kubectl_manifest" "sysbox" {
      + api_version             = "v1"
      + apply_only              = false
      + field_manager           = "kubectl"
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "ServiceAccount"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "sysbox-label-node"
      + namespace               = "kube-system"
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: sysbox-label-node
              namespace: kube-system
        EOT
      + yaml_incluster          = (sensitive value)
    }
```

Is this on purpose or could i consider this as a bug?
