### ISSUE TITLE
How to inject yaml into a yaml file

### ISSUE THREAD

**Issue by jorgemoralespou** [alekc/terraform-provider-kubectl#55]
I need to make part of a yaml snippet configurable, but I don't really know how this can be achieved with module. I've tried to options:
I need to inject this snippet:
```
config:
  item:
    key: value
```

Into a bigger document:

Injecting directly into a YAML hardcoded snippet:
```
locals {
  config = try(yamldecode(file('config.yaml')), {})
}

resource "kubectl_manifest" "app_package_installs_workshops_package" {
 
  yaml_body = <<YAML
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config
    data:
       config.yaml:  ${yamlencode(local.config)}
YAML
```

This is not producing what I would expect:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
   config.yaml:  "config"
"item":
  "key": "value"
```
 
I've tried with a `kubectl_path_documents` with same results. Can you give me any guidance?
